modLoader="javafml"
loaderVersion="${fmlVersionRange}"
issueTrackerURL="https://github.com/christopherwalkerml/MoBees/issues"

license="GNU GPLv3"

[[mods]]
modId="mobeeshatched"
version="${version}"
displayName="MoBees"
credits="binnie, thedarkcolour"
authors="Chris Walker (noodlepfp)"
description='''
	More Bees for Forestry CE Mod
	'''

[[dependencies.mobeeshatched]]
modId="minecraft"
mandatory=true
versionRange="${minecraftVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.mobeeshatched]]
modId="forge"
mandatory=true
versionRange="${forgeVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.mobeeshatched]]
modId="patchouli"
mandatory=true
versionRange="${patchouliVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.mobeeshatched]]
modId="forestry"
mandatory=true
versionRange="${forestryVersionRange}"
ordering="NONE"
side="CLIENT"

[[dependencies.mobeeshatched]]
modId="jei"
mandatory=false
versionRange="${jeiVersionRange}"
ordering="NONE"
side="CLIENT"
